/*
 * Copyright (C) filoghost and contributors
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
package me.filoghost.holographicdisplays.disk;

import me.filoghost.fcommons.config.Config;
import me.filoghost.fcommons.config.ConfigPath;
import me.filoghost.fcommons.config.ConfigSection;
import me.filoghost.fcommons.config.ConfigType;
import me.filoghost.fcommons.logging.Log;
import me.filoghost.holographicdisplays.commands.Messages;
import me.filoghost.holographicdisplays.core.Utils;
import me.filoghost.holographicdisplays.object.internal.InternalHologram;
import me.filoghost.holographicdisplays.object.internal.InternalHologramManager;
import org.bukkit.command.CommandSender;

import java.util.ArrayList;
import java.util.List;
import java.util.Map.Entry;

public class HologramDatabase {

    private static List<HologramConfig> hologramConfigs;

    public void loadFromConfig(Config config) {
        hologramConfigs = new ArrayList<>();

        for (Entry<ConfigPath, ConfigSection> entry : config.toMap(ConfigType.SECTION).entrySet()) {
            String hologramName = entry.getKey().asRawKey();
            ConfigSection hologramSection = entry.getValue();

            HologramConfig hologramConfig = new HologramConfig(hologramName, hologramSection);
            hologramConfigs.add(hologramConfig);
        }
    }

    public void createHolograms(CommandSender sender, InternalHologramManager internalHologramManager) {
        for (HologramConfig hologramConfig : hologramConfigs) {
            try {
                hologramConfig.createHologram(internalHologramManager);
            } catch (HologramLoadException e) {
                if (sender != null) {
                    Messages.sendWarning(sender, Utils.formatExceptionMessage(e));
                } else {
                    Log.warning(Utils.formatExceptionMessage(e));
                }
            } catch (Exception e) {
                Log.warning("Unexpected exception while loading the hologram \"" + hologramConfig.getName() + "\".", e);
            }
        }
    }

    public static Config exportToConfig(InternalHologramManager hologramManager) {
        Config config = new Config();

        for (InternalHologram hologram : hologramManager.getHolograms()) {
            config.setConfigSection(hologram.getName(), new HologramConfig(hologram).toConfigSection());
        }

        config.setHeader(
                "",
                "Please do NOT edit this file manually if possible.",
                ""
        );

        return config;
    }

}
